### ISSUE TITLE
Run under cygwin

### ISSUE THREAD

**Issue by mrgloom** [ai-ku/wkmeans#1]
I tried to run it under cygwin and it just freeze - no output.

Another question what format of input\output? Did you compare speed\accuracy with sofia-ml kmeans?

**Comment by esert** [comment]
We never ran it in cygwin, but are you sure it froze? It may be waiting for the input.

I've just updated the README, but let me paste it here as well:

```
Input format (assuming you have m vectors of n dimensions):
[label_1] [weight_1] x_11 ... x_1m
...
[label_m] [weight_m] x_m1 ... x_mn

label_i  : (string) label of the ith vector, required when -l used
weight_i : (double) weight of the ith vector, required when -w used
x_ij     : (double) ith vector's jth component

Output format:
[label_1] c_1
...
[label_m] c_m

c_i : (int) cluster of ith vector
```

As far as I know none of us compared this with sofia-ml kmeans.

**Comment by mrgloom** [comment]
I tried to run it under amazon ec2 ubuntu, same result.

`git clone https://github.com/ai-ku/wkmeans.git`
`cd wkmeans`
`make`

`./wkmeans`
nothing happens
 `./wkmeans -k 2 data.txt out.txt`
nothing happens

data.txt for test
1 2 3 4
11 2.1 3 4
142.01 2 3 5

**Comment by esert** [comment]
wkmeans doesn't do anything with the command line arguments, you have to redirect the input/output, like this:

`./wkmeans -k 2 < data.txt > out.txt`

**Comment by mrgloom** [comment]
still can't make it work

when I use 
`./wkmeans -k 2 < data.txt > out.txt`

one core stay busy and nothing happens and it's weird for data.txt file consisting of several lines. 

can you provide small working example?
